#-------------------------------
# 基本
#-------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
if = 'has("unix") || has("mac")'
build = 'make'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/deol.nvim'

# [[plugins]]
# repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'  # for Denite

[[plugins]]
repo = 'Shougo/neoyank.vim'  # for Denite

# [[plugins]]
# repo = 'Townk/vim-autoclose'        # カッコやダブルコーテーションを自動で閉じる

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
  let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tyru/caw.vim.git'           # コメントアウト

[[plugins]]
repo = 'itchyny/lightline.vim'

# [[plugins]]
# repo = 'vim-airline/vim-airline'

# [[plugins]]
# repo = 'vim-airline/vim-airline-themes'

[[plugins]]                         # Bcloseコマンド
repo = 'rbgrouleff/bclose.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'godlygeek/tabular'

# [[plugins]]
# repo = 'szw/vim-tags'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'majutsushi/tagbar'


# [[plugins]]
# repo = 'bagrat/vim-buffet'
# hook_add = '''
#   let g:buffet_powerline_separators = 1
# '''


#-------------------------------
# Git
#-------------------------------
[[plugins]]
repo = 'airblade/vim-gitgutter' # 左側の差分表示

[[plugins]]
repo = 'tpope/vim-fugitive' # Gstatusなど

[[plugins]]
repo = 'tpope/vim-rhubarb' # Gbrowseコマンド用

[[plugins]]
repo = 'cohama/agit.vim' # Agitコマンド。git logの整形



#-------------------------------
# 補完
#-------------------------------
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete.vim'
#
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-buffer.vim'
#
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-emoji.vim'
#
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-file.vim'
#
# [[plugins]]
# repo = 'yami-beta/asyncomplete-omni.vim'
#
# [[plugins]]
# repo = 'Shougo/neco-vim'
#
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-necovim.vim'
#
# [[plugins]]
# repo = 'prabirshrestha/async.vim'
#
# [[plugins]]
# repo = 'prabirshrestha/vim-lsp'
#
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-lsp.vim'
# build = '''
#   gem install solargraph
#   npm install -g typescript typescript-language-server
#   npm install -g vscode-css-languageserver-bin
#   npm install -g vue-language-server
#   pip3 install python-language-server
# '''
#
# [[plugins]]
# repo = 'ryanolsonx/vim-lsp-typescript'
#
# [[plugins]]
# repo = 'ryanolsonx/vim-lsp-javascript'


[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

# [[plugins]]
# repo = 'Shougo/deoppet.nvim'
#
# [[plugins]]
# repo = 'Shougo/deoppet-snippets'
# depends = ['deoppet']

[[plugins]]
if = '!has("nvim")'
repo = 'roxma/nvim-yarp'  # Vimでdeopleteを動かすのに必須。neovimでは不要。

[[plugins]]
if = '!has("nvim")'
repo = 'roxma/vim-hug-neovim-rpc'  # Vimでdeopleteを動かすのに必須。neovimでは不要。

[[plugins]]
repo = 'Shougo/neco-vim'
depends = ['deoplete']

[[plugins]]
repo = 'Shougo/neco-syntax'
depends = ['deoplete']

[[plugins]]
repo = 'ujihisa/neco-look'  # English
depends = ['deoplete']

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
depends = ['deoplete']
rev = 'next'
if = 'has("win32")'
build = '''
  powershell -executionpolicy bypass -File install.ps1
  gem install solargraph
  npm install -g javascript-typescript-langserver
  npm install -g vscode-css-languageserver-bin
  npm install -g vue-language-server
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
depends = ['deoplete']
rev = 'next'
if = '!has("win32")'
build = '''
  bash install.sh
  gem install solargraph
  npm install -g javascript-typescript-langserver
  npm install -g vscode-css-languageserver-bin
  npm install -g vue-language-server
  pip3 install python-language-server
'''

[[plugins]] # for LanguageClient-neovim
repo = 'junegunn/fzf'

#-------------------------------
# カラースキーマ
#-------------------------------
# [[plugins]]
# repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

# [[plugins]]
# repo = 'tomasr/molokai'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

#[[plugins]]
#repo = 'jonathanfilip/vim-lucius'

#[[plugins]]
#repo = 'jpo/vim-railscasts-theme'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

# [[plugins]]
# repo = 'felipesousa/rupza'

[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

#-------------------------------
# lazyだと動きがおかしいもの
#-------------------------------

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'thinca/vim-ref'
build = '''
  gem install refe2
'''


