#-------------------------------
# 基本
#-------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
if = 'has("unix") || has("mac")'
build = 'make'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/unite.vim'

#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplete'

[[plugins]]
repo = 'Townk/vim-autoclose'        # カッコやダブルコーテーションを自動で閉じる

[[plugins]]
repo = 'kien/ctrlp.vim.git'         # コマンドラインでのファイル補完

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tyru/caw.vim.git'           # コメントアウト

[[plugins]]
repo = 'itchyny/lightline.vim'

#[[plugins]]
#repo = 'Yggdroot/indentLine'


# [[plugins]]
# repo = 'rhysd/accelerated-jk'       # j,kでの移動の高速化
# hook_add = '''
# 	nmap j <Plug>(accelerated_jk_gj)
# 	nmap k <Plug>(accelerated_jk_gk)
# '''



#-------------------------------
# カラースキーマ
#-------------------------------
#[[plugins]]
#repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'tomasr/molokai'

#[[plugins]]
#repo = 'crusoexia/vim-monokai'

#[[plugins]]
#repo = 'nanotech/jellybeans.vim'

#[[plugins]]
#repo = 'w0ng/vim-hybrid'

#[[plugins]]
#repo = 'jonathanfilip/vim-lucius'

#[[plugins]]
#repo = 'jpo/vim-railscasts-theme'




