#-------------------------------
# 基本
#-------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
if = 'has("unix") || has("mac")'
build = 'make'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/unite.vim'

#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplete'
if = '!has("nvim")'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
hook_add = '''
	let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Townk/vim-autoclose'        # カッコやダブルコーテーションを自動で閉じる

[[plugins]]
repo = 'kien/ctrlp.vim.git'         # コマンドラインでのファイル補完

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tyru/caw.vim.git'           # コメントアウト

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]                         # Bcloseコマンド
repo = 'rbgrouleff/bclose.vim'

#[[plugins]]
#repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'


#-------------------------------
# カラースキーマ
#-------------------------------
#[[plugins]]
#repo = 'altercation/vim-colors-solarized'

# [[plugins]]
# repo = 'tomasr/molokai'

#[[plugins]]
#repo = 'crusoexia/vim-monokai'

#[[plugins]]
#repo = 'nanotech/jellybeans.vim'

#[[plugins]]
#repo = 'w0ng/vim-hybrid'

#[[plugins]]
#repo = 'jonathanfilip/vim-lucius'

#[[plugins]]
#repo = 'jpo/vim-railscasts-theme'

# [[plugins]]
# repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

# [[plugins]]
# repo = 'felipesousa/rupza'
#
# [[plugins]]
# repo = 'dracula/vim'
#
# [[plugins]]
# repo = 'jonathanfilip/vim-lucius'


